spring:
        datasource:
                driver-class-name: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/agreements
                username: postgres
                password: postgres
                hikari:
                        schema: public
server:
        error:
                include-message: always
#logging:
#        file.name: C:\tmp\app\authlogfileload.log
#        pattern:
#                console: "%d %-5level %logger : %msg%n"
#                file: "%d %-5level [%thread] %logger : %msg%n"
#        level:
#                org.springframework.web: ERROR
#                com.howtodoinjava: DEBUG
#                org.hibernate: ERROR
#logfiles:
#        authlogpath: C:\tmp
#        authlogextension: log
