spring:
        datasource:
                driver-class-name: org.postgresql.Driver
                url: jdbc:postgresql://localhost:5432/agreements
                username: postgres
                password: postgres
                hikari:
                        schema: public
server:
        error:
                include-message: always

